services:
  oneapi:
    image: ghcr.io/songquanpeng/one-api:v0.6.6
    container_name: oneapi
    restart: on-failure:3
    ports:
      - '3000:3000'
    environment:
      TZ: 'Asia/Shanghai'
      SQL_DSN: 'oneapi:oneapi@tcp(db:3306)/oneapi'   # 用户名和密码,这里单独创建了一个数据库
    networks:
      - oneapi
    volumes:
      - './oneapi/data:/data'
    command: ["./wait-for-it.sh", "mysql:3306", "--", "npm", "start"]    
    depends_on:
      mysql:
        condition: service_healthy    

  db:
    image: mysql:5.7.42
    container_name: oneapi_db
    restart: on-failure:3
    environment:
      TZ: 'Asia/Shanghai'
      MYSQL_ROOT_PASSWORD: Hv260i6ep218e7Y
      MYSQL_DATABASE: 'oneapi'
      MYSQL_USER: 'oneapi'
      MYSQL_PASSWORD: 'oneapi'
    networks:
      - oneapi
    volumes:
      - './mysql/conf:/etc/mysql'
      - './mysql/data:/var/lib/mysql'
      - './mysql/log:/var/log/mysql'
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin --user=root --password=Hv260i6ep218e7Y ping -h localhost"]
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 10s

networks:
  oneapi:
    driver: bridge
