services:
  nginx:
    image: nginx:1.25.2
    container_name: nginx
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
      - 443:443/udp
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./conf.d:/etc/nginx/conf.d
      - ./certs:/etc/nginx/certs
      - ./html:/var/www/html
      - ./log:/var/log/nginx
      - /etc/localtime:/etc/localtime:ro  # 挂载本地时区文件
      - /etc/timezone:/etc/timezone:ro    # 挂载本地时区配置
    tmpfs:
    # - /var/cache/nginx:rw,noexec,nosuid,size=512m
      - /var/cache/fst_cache:rw,noexec,nosuid,size=512m
      - /var/cache/ngx_cache:rw,noexec,nosuid,size=512m
    networks:
      - nginx

networks:
  nginx:
    driver: bridge
