services:
  nginx:
    image: nginx:1.25.2
    container_name: nginx
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
      - 443:443/udp
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./conf.d:/etc/nginx/conf.d
      - ./certs:/etc/nginx/certs
      - ./html:/var/www/html
      - ./log:/var/log/nginx
      - /etc/localtime:/etc/localtime:ro  # 挂载本地时区文件
      - /etc/timezone:/etc/timezone:ro    # 挂载本地时区配置
    tmpfs:
    # noexec: 禁止在tmpfs上执行可执行文件,增加安全性,防止恶意代码执行
    # nosuid: 禁止设置setuid和setgid权限,同样是为了安全考虑,避免潜在的安全漏洞
    # size=512m: 指定tmpfs的大小为512MB,这限制了tmpfs的最大使用空间
      - /var/cache/nginx:rw,noexec,nosuid,size=512m
    networks:
      - nginx

networks:
  nginx:
    driver: bridge
